baseURL = "https://lian-book.github.io/"
languageCode = "zh-cn"
title = "Lian's Book"
theme = "PaperMod"

[params]
mainSections = []
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowReadingTime = false
